Uninstall locale from all themes
wp-cli/language-command pull request #124
Opened 2023-08-24 18:12 UTC by atoomic

Refs: #122

Add support for '--all' to the Theme
uninstall function.

Switch the report output to use a table
and support for json.

2023-08-24 18:13 UTC, atoomic commented
Install example:
```
[wpaccount@sandbox-c8-fat ~]$ ~/ww language theme install --all fr_FR
Using cached file '/home/wpaccount/.wp-cli/cache/translation/theme-twentytwentyone-1.0-fr_FR-1647106647.zip'...
Unpacking the update...
Installing the latest version...
Removing the old version of the translation...
Translation updated successfully.
Language 'fr_FR' for 'Twenty Twenty-One' installed.
Using cached file '/home/wpaccount/.wp-cli/cache/translation/theme-twentytwentythree-1.2-fr_FR-1667221284.zip'...
Unpacking the update...
Installing the latest version...
Removing the old version of the translation...
Translation updated successfully.
Language 'fr_FR' for 'Twenty Twenty-Three' installed.
Using cached file '/home/wpaccount/.wp-cli/cache/translation/theme-twentytwentytwo-1.4-fr_FR-1680121959.zip'...
Unpacking the update...
Installing the latest version...
Removing the old version of the translation...
Translation updated successfully.
Language 'fr_FR' for 'Twenty Twenty-Two' installed.
Warning: Language 'fr_FR' not available.
Language 'fr_FR' for 'UniBlock' not installed.
Success: Installed 3 of 4 languages (1 skipped).
+-------------------+--------+---------------+
| name              | locale | status        |
+-------------------+--------+---------------+
| twentytwentyone   | fr_FR  | installed     |
| twentytwentythree | fr_FR  | installed     |
| twentytwentytwo   | fr_FR  | installed     |
| uniblock          | fr_FR  | not available |
+-------------------+--------+---------------+
```

Uninstall example:
```
> wp language theme uninstall --all fr_FR
Language 'fr_FR' for 'twentytwentyone' uninstalled.
Language 'fr_FR' for 'twentytwentythree' uninstalled.
Language 'fr_FR' for 'twentytwentytwo' uninstalled.
Language fr_FR not installed.
Success: Language already uninstalled.
+-------------------+--------+---------------+
| name              | locale | status        |
+-------------------+--------+---------------+
| twentytwentyone   | fr_FR  | uninstalled   |
| twentytwentythree | fr_FR  | uninstalled   |
| twentytwentytwo   | fr_FR  | uninstalled   |
| uniblock          | fr_FR  | not installed |
+-------------------+--------+---------------+
```

2023-08-24 18:35 UTC, atoomic commented on src/Theme_Language_Command.php
> +		\WP_CLI\Utils\report_batch_operation_results( 'language', 'uninstall', $count, $successes, $errors, $skips );
should do the trick 
```
$count = count( $themes ) * count( $language_codes );
```

2023-08-24 18:37 UTC, atoomic commented
note: need to adjust and add some unit tests 
the `uninstall` is now using a table output

2023-08-24 18:48 UTC, atoomic commented
fixed phpcs

2023-08-24 22:37 UTC, atoomic commented
fixed and added some tests

2023-08-29 11:30 UTC, swissspidy approved these changes
Really nice work, thank you!

Would you also be open to add the same for plugins next? :-)

2023-08-29 22:10 UTC, danielbachhuber requested changes

2023-08-29 22:10 UTC, danielbachhuber commented on features/language-theme.feature
> +    And STDERR should be empty
Can we add a scenario for neither `<theme>` nor `--all` is provided?

2023-08-29 22:10 UTC, danielbachhuber commented on src/Theme_Language_Command.php
> +		/* process all themes */
This comment is extraneous and can be removed.

2023-10-18 13:16 UTC, danielbachhuber approved these changes

2023-10-18 13:18 UTC, merged